<?php
/**
 * Compare — optional "Site Compare" tool page (source vs. target visual gallery).
 *
 * Admin surface + AJAX bridge for a node-based full-page screenshot comparison
 * tool: every URL harvested from the SOURCE site's sitemap (the "URL scraper")
 * is captured on both the source and the target origin and rendered side by
 * side in an HTML gallery. The gallery itself is generated by the host's
 * capture tool (node) into the uploads dir; this class only:
 *
 *  - registers a submenu page with a settings form (source base / source
 *    sitemap / target base — stored in a prefix-scoped option, boot config
 *    provides the defaults),
 *  - embeds the WP-served gallery in a same-origin iframe
 *    (`?wp=1&ajax=<admin-ajax>&nonce=…&action=…` — the gallery HTML lives
 *    under uploads on the SAME origin as wp-admin, so its JS can call
 *    admin-ajax.php directly: no CORS, no mixed content, no control server),
 *  - bridges refresh / regenerate / stop / status through admin-ajax by
 *    shelling out to node (needs `shell_exec` + node + the host's tool).
 *
 * Entirely opt-in: instantiated by Plugin only when the host passes a
 * `compare` config array to Plugin::boot(). Without it the feature is inert.
 *
 *     Plugin::boot( 'my_prefix', array(
 *         'compare' => array(
 *             'source_base'    => 'https://www.example.com',
 *             'source_sitemap' => 'https://www.example.com/sitemap_index.xml',
 *             'target_base'    => 'https://example.local',
 *             'wrapper'        => '/path/to/bin/visual-compare.sh',
 *             'tool_dir'       => '/path/to/bin/visual-compare',
 *         ),
 *     ) );
 *
 * Hard-won lessons carried over from the original (Wolfe's Neck) module:
 *  - the run mode is validated by regex on the RAW POST value — sanitize_key()
 *    would strip the colon out of `type:<slug>`;
 *  - a regenerate run is "in progress" only if its lock-file PID is a LIVE
 *    process (posix_kill / `kill -0`), so a crashed run never leaves a
 *    phantom "capturing…" state;
 *  - node's directory is prepended to PATH for the detached shell — php-fpm's
 *    spawned shell often has a minimal PATH without node.
 */

namespace BinaryWP\AdminGuide;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class Compare {

	/** @var Context */
	private $context;

	/** @var array Boot-time `compare` config (defaults; saved settings win). */
	private $args;

	/** @var string */
	private $page_slug;

	/** @var array|null Lazily resolved tool/paths config. */
	private $resolved;

	/**
	 * @param Context $context Instance context.
	 * @param array   $args {
	 *     Compare feature config (all keys optional).
	 *
	 *     @type string $source_base    Default source (production) origin URL.
	 *     @type string $source_sitemap Default source sitemap index URL (the URL scraper input).
	 *     @type string $target_base    Default target (local) origin URL. Falls back to home_url().
	 *     @type string $output_rel     Uploads-relative gallery dir. Default 'migrate/compare'.
	 *     @type string $wrapper        Absolute path to the capture shell wrapper.
	 *     @type string $tool_dir       Absolute path to the node tool dir. Defaults to $wrapper minus '.sh'.
	 *     @type string $node_bin       Node binary override. Default /usr/local/bin/node, else `command -v node`.
	 *     @type string $menu_label     Submenu label. Default 'Site Compare'.
	 *     @type string $capability     Capability for the page + handlers. Default = package capability.
	 * }
	 */
	public function __construct( Context $context, array $args = array() ) {
		$this->context   = $context;
		$this->args      = $args;
		// URL: ?page={prefix}-admin-guide-compare
		$this->page_slug = $context->page_slug( 'compare' );

		add_action( 'admin_menu', array( $this, 'register_menu' ), 26 );
		add_action( 'admin_post_' . $context->action_name( 'compare_save_settings' ), array( $this, 'handle_save_settings' ) );

		add_action( 'wp_ajax_' . $context->action_name( 'compare_refresh' ), array( $this, 'ajax_refresh' ) );
		add_action( 'wp_ajax_' . $context->action_name( 'compare_regenerate' ), array( $this, 'ajax_regenerate' ) );
		add_action( 'wp_ajax_' . $context->action_name( 'compare_stop' ), array( $this, 'ajax_stop' ) );
		add_action( 'wp_ajax_' . $context->action_name( 'compare_status' ), array( $this, 'ajax_status' ) );
		add_action( 'wp_ajax_' . $context->action_name( 'compare_refresh_sitemap' ), array( $this, 'ajax_refresh_sitemap' ) );
	}

	// ── Config resolution ───────────────────────────────────────────────

	/** Capability required for the page + all handlers. */
	private function capability() {
		return ! empty( $this->args['capability'] ) ? (string) $this->args['capability'] : $this->context->capability;
	}

	/**
	 * Effective URL settings: prefix-scoped option wins over boot defaults.
	 *
	 * @return array{source_base:string,source_sitemap:string,target_base:string}
	 */
	public function settings() {
		$defaults = array(
			'source_base'    => isset( $this->args['source_base'] ) ? (string) $this->args['source_base'] : '',
			'source_sitemap' => isset( $this->args['source_sitemap'] ) ? (string) $this->args['source_sitemap'] : '',
			'target_base'    => isset( $this->args['target_base'] ) ? (string) $this->args['target_base'] : home_url(),
		);
		$saved = get_option( $this->context->option_key( 'compare' ), array() );
		if ( is_array( $saved ) ) {
			foreach ( $defaults as $key => $default ) {
				if ( isset( $saved[ $key ] ) && '' !== trim( (string) $saved[ $key ] ) ) {
					$defaults[ $key ] = (string) $saved[ $key ];
				}
			}
		}
		return $defaults;
	}

	/**
	 * Resolve tool + output paths (cached per request).
	 *
	 * @return array{node:string,tool_dir:string,wrapper:string,out_dir:string,out_url:string,shell:bool,ready:bool,missing:string[]}
	 */
	private function config() {
		if ( null !== $this->resolved ) {
			return $this->resolved;
		}

		$wrapper  = isset( $this->args['wrapper'] ) ? (string) $this->args['wrapper'] : '';
		$tool_dir = isset( $this->args['tool_dir'] ) ? (string) $this->args['tool_dir'] : '';
		if ( '' === $tool_dir && '' !== $wrapper ) {
			// Convention: bin/visual-compare.sh wraps bin/visual-compare/.
			$tool_dir = preg_replace( '/\.sh$/', '', $wrapper );
		}

		// node binary — php-fpm's PATH often lacks it, so default to an
		// absolute path and fall back to `command -v node`.
		$node = ! empty( $this->args['node_bin'] ) ? (string) $this->args['node_bin'] : '/usr/local/bin/node';
		if ( ! is_executable( $node ) && $this->shell_available() ) {
			$found = trim( (string) @shell_exec( 'command -v node 2>/dev/null' ) );
			if ( '' !== $found ) {
				$node = $found;
			}
		}

		$output_rel = ! empty( $this->args['output_rel'] ) ? (string) $this->args['output_rel'] : 'migrate/compare';
		$output_rel = trim( $output_rel, '/' );

		$up    = wp_upload_dir();
		$shell = $this->shell_available();

		// Everything the toolbar needs to actually run captures. Missing pieces
		// degrade gracefully: settings + read-only gallery keep working.
		$missing = array();
		if ( ! $shell ) {
			$missing[] = 'shell_exec';
		}
		if ( '' === $wrapper || ! file_exists( $wrapper ) ) {
			$missing[] = 'wrapper';
		}
		if ( '' === $tool_dir || ! is_dir( $tool_dir ) ) {
			$missing[] = 'tool_dir';
		}
		if ( ! is_executable( $node ) ) {
			$missing[] = 'node';
		}

		$this->resolved = array(
			'node'     => $node,
			'tool_dir' => rtrim( $tool_dir, '/' ),
			'wrapper'  => $wrapper,
			'out_dir'  => $up['basedir'] . '/' . $output_rel,
			'out_url'  => $up['baseurl'] . '/' . $output_rel,
			'shell'    => $shell,
			'ready'    => empty( $missing ),
			'missing'  => $missing,
		);
		return $this->resolved;
	}

	/** shell_exec present and not disabled? */
	private function shell_available() {
		if ( ! function_exists( 'shell_exec' ) ) {
			return false;
		}
		$disabled = array_map( 'trim', explode( ',', (string) ini_get( 'disable_functions' ) ) );
		return ! in_array( 'shell_exec', $disabled, true );
	}

	// ── Run-state helpers (lock / log / PID liveness) ───────────────────

	private function lock_file( array $cfg ) {
		return $cfg['out_dir'] . '/.regen.lock';
	}

	private function log_file( array $cfg ) {
		return $cfg['out_dir'] . '/.regen.log';
	}

	/**
	 * A regenerate run is "in progress" only if its process is actually ALIVE.
	 * The detached run writes its shell PID into the lock as its first act and
	 * removes the lock when it exits — but a hard crash / kill / OOM leaves the
	 * lock behind. So we check the PID is a live process (not just that the
	 * file exists), which makes the admin recover instantly from a died run
	 * instead of showing a phantom "capturing…". A just-claimed lock with no
	 * PID yet gets a short grace window.
	 */
	private function is_running( array $cfg ) {
		$lock = $this->lock_file( $cfg );
		if ( ! file_exists( $lock ) ) {
			return false;
		}
		$pid = (int) trim( (string) @file_get_contents( $lock ) );
		if ( $pid > 0 ) {
			if ( $this->pid_alive( $pid ) ) {
				return true;
			}
			@unlink( $lock ); // process gone → stale lock
			return false;
		}
		// No PID written yet (just claimed): brief grace, else treat as stale.
		if ( ( time() - (int) filemtime( $lock ) ) < 30 ) {
			return true;
		}
		@unlink( $lock );
		return false;
	}

	/** Is process $pid alive? posix if available, else `kill -0`. */
	private function pid_alive( $pid ) {
		$pid = (int) $pid;
		if ( function_exists( 'posix_kill' ) ) {
			return @posix_kill( $pid, 0 );
		}
		if ( $this->shell_available() ) {
			return trim( (string) shell_exec( 'kill -0 ' . $pid . ' 2>/dev/null; echo $?' ) ) === '0';
		}
		return false; // can't tell → assume not running (recover)
	}

	/** Absolute path of $bin if on PATH (or a known abs path), else ''. */
	private function which( $bin ) {
		if ( ! $this->shell_available() ) {
			return '';
		}
		$p = trim( (string) @shell_exec( 'command -v ' . escapeshellarg( $bin ) . ' 2>/dev/null' ) );
		if ( '' === $p ) {
			// fpm PATH is often minimal — probe the usual absolute locations.
			foreach ( array( '/usr/bin/' . $bin, '/bin/' . $bin, '/usr/local/bin/' . $bin, '/opt/homebrew/bin/' . $bin ) as $abs ) {
				if ( is_executable( $abs ) ) {
					return $abs;
				}
			}
			return '';
		}
		return is_executable( $p ) ? $p : '';
	}

	/**
	 * Launch $inner as a background process that SURVIVES the current request.
	 * php-fpm reaps the request's child process group on teardown, so a bare
	 * `nohup … &` dies before it runs anything on macOS (which ships no `setsid`
	 * binary). Detach into a NEW SESSION instead. Preference:
	 *   1. `setsid` (Linux) — new session, immune to the reap.
	 *   2. python3 double-fork + os.setsid() (macOS/Local) — same effect, no binary.
	 *   3. `nohup … &` — last-resort fallback.
	 */
	private function spawn_detached( $inner ) {
		if ( ! $this->shell_available() ) {
			return;
		}
		$setsid = $this->which( 'setsid' );
		if ( '' !== $setsid ) {
			shell_exec( sprintf( 'nohup %s sh -c %s >/dev/null 2>&1 &', escapeshellarg( $setsid ), escapeshellarg( $inner ) ) );
			return;
		}
		$python = $this->which( 'python3' );
		if ( '' !== $python ) {
			// Classic daemonize: fork → setsid → fork → exec. The grandchild is a
			// session leader with no controlling terminal, reparented to init, so
			// the fpm request teardown can't signal it.
			$script = "import os,sys\n"
				. "if os.fork(): os._exit(0)\n"
				. "os.setsid()\n"
				. "if os.fork(): os._exit(0)\n"
				. "dn=os.open('/dev/null',os.O_RDWR); os.dup2(dn,0)\n"
				. "os.execv('/bin/sh',['/bin/sh','-c',sys.argv[1]])\n";
			shell_exec( escapeshellarg( $python ) . ' -c ' . escapeshellarg( $script ) . ' ' . escapeshellarg( $inner ) );
			return;
		}
		shell_exec( sprintf( 'nohup sh -c %s >/dev/null 2>&1 &', escapeshellarg( $inner ) ) );
	}

	// ── Manifest helpers ────────────────────────────────────────────────

	/** Decoded manifest.json, or null when absent/invalid. */
	private function manifest( array $cfg ) {
		$fp = $cfg['out_dir'] . '/manifest.json';
		if ( ! file_exists( $fp ) ) {
			return null;
		}
		$m = json_decode( (string) file_get_contents( $fp ), true );
		return is_array( $m ) ? $m : null;
	}

	/**
	 * Decoded sitemap.json — the SOURCE inventory (per-type counts + path list)
	 * written by a `--harvest-only` pass ("Refresh sitemap data"). This is what
	 * keeps the source page/type info valid independent of the last capture run,
	 * so switching the sitemap URL no longer leaves a stale count behind.
	 *
	 * @return array|null
	 */
	private function sitemap_data( array $cfg ) {
		$fp = $cfg['out_dir'] . '/sitemap.json';
		if ( ! file_exists( $fp ) ) {
			return null;
		}
		$d = json_decode( (string) file_get_contents( $fp ), true );
		return is_array( $d ) ? $d : null;
	}

	/**
	 * Distinct sub-sitemap types (slug => count) that back the per-type source
	 * options. Prefers the harvested sitemap.json (current source inventory,
	 * refreshable without a capture); falls back to the capture manifest so
	 * older reports still populate the dropdown.
	 *
	 * @return array<string,int>
	 */
	private function types( array $cfg ) {
		$s = $this->sitemap_data( $cfg );
		if ( $s && ! empty( $s['types'] ) && is_array( $s['types'] ) ) {
			return array_map( 'intval', $s['types'] );
		}
		$m     = $this->manifest( $cfg );
		$types = array();
		foreach ( ( $m ? ( isset( $m['pages'] ) ? (array) $m['pages'] : array() ) : array() ) as $p ) {
			$t = isset( $p['type'] ) ? $p['type'] : null;
			if ( is_string( $t ) && '' !== $t ) {
				$types[ $t ] = ( isset( $types[ $t ] ) ? $types[ $t ] : 0 ) + 1;
			}
		}
		return $types;
	}

	/** One-line SOURCE sitemap summary ("N URLs · M types · refreshed …"), or ''. */
	private function source_summary( array $cfg ) {
		$s = $this->sitemap_data( $cfg );
		if ( ! $s ) {
			return '';
		}
		return sprintf(
			/* translators: 1: URL count, 2: type count, 3: timestamp */
			__( '%1$d URLs · %2$d types · refreshed %3$s', 'binary-wp-admin-guide' ),
			isset( $s['total'] ) ? (int) $s['total'] : 0,
			isset( $s['types'] ) ? count( (array) $s['types'] ) : 0,
			isset( $s['generatedAt'] ) ? (string) $s['generatedAt'] : '?'
		);
	}

	/**
	 * Build the `--harvest-only` command (source inventory refresh, no browser).
	 * Synchronous + quick: just fetches the sitemap XML and writes sitemap.json.
	 *
	 * @return string|null Shell command, or null when the tool isn't runnable.
	 */
	private function harvest_command( array $cfg ) {
		if ( ! $cfg['ready'] ) {
			return null;
		}
		$settings = $this->settings();
		$sitemap  = isset( $settings['source_sitemap'] ) ? (string) $settings['source_sitemap'] : '';
		if ( '' === $sitemap ) {
			return null;
		}
		return sprintf(
			'export PATH=%s:"$PATH"; %s %s --harvest-only --sitemap %s --out %s 2>&1',
			escapeshellarg( dirname( $cfg['node'] ) ),
			escapeshellarg( $cfg['node'] ),
			escapeshellarg( $cfg['tool_dir'] . '/capture.mjs' ),
			escapeshellarg( $sitemap ),
			escapeshellarg( $cfg['out_dir'] )
		);
	}

	/** One-line manifest summary ("N pages · mode · run …"), or ''. */
	private function summary( array $cfg ) {
		$m = $this->manifest( $cfg );
		if ( ! $m ) {
			return '';
		}
		return sprintf(
			'%d pages · %s · run %s',
			count( isset( $m['pages'] ) ? (array) $m['pages'] : array() ),
			isset( $m['mode'] ) ? (string) $m['mode'] : 'sitemap',
			isset( $m['generatedAt'] ) ? (string) $m['generatedAt'] : '?'
		);
	}

	/**
	 * Keep only path-shaped strings (`/foo/bar/`). The paths originate from
	 * the gallery's own manifest, but we still validate before handing them
	 * to a shell.
	 *
	 * @param array $paths
	 * @return string[]
	 */
	private function sanitize_paths( array $paths ) {
		$clean = array();
		foreach ( $paths as $p ) {
			$p = (string) $p;
			if ( '' !== $p && preg_match( '#^/[A-Za-z0-9/_.\-]*$#', $p ) ) {
				$clean[] = $p;
			}
		}
		return array_values( array_unique( $clean ) );
	}

	// ── Menu / page ─────────────────────────────────────────────────────

	public function register_menu() {
		$menu   = $this->context->menu_defaults;
		$parent = ! empty( $menu['parent'] ) ? $menu['parent'] : 'tools.php';
		$label  = ! empty( $this->args['menu_label'] ) ? (string) $this->args['menu_label'] : __( 'Site Compare', 'binary-wp-admin-guide' );

		add_submenu_page(
			$parent,
			$label,
			$label,
			$this->capability(),
			$this->page_slug,
			array( $this, 'render_page' )
		);
	}

	public function render_page() {
		$cfg      = $this->config();
		$settings = $this->settings();

		$manifest_fp = $cfg['out_dir'] . '/manifest.json';
		$index_fp    = $cfg['out_dir'] . '/index.html';
		$has_gallery = file_exists( $index_fp ) && file_exists( $manifest_fp );

		$refresh_nonce = wp_create_nonce( $this->context->nonce_action( 'compare_refresh' ) );
		$ctl_nonce     = wp_create_nonce( $this->context->nonce_action( 'compare_ctl' ) );

		// iframe src in WP interactive mode: same-origin admin-ajax + nonce +
		// the prefix-scoped refresh action name (the gallery JS reads them off
		// its own query string).
		$iframe_src = add_query_arg(
			array(
				'wp'     => '1',
				'ajax'   => rawurlencode( admin_url( 'admin-ajax.php' ) ),
				'nonce'  => $refresh_nonce,
				'action' => $this->context->action_name( 'compare_refresh' ),
				'cb'     => (string) time(), // dodge browser cache on the html itself
			),
			$cfg['out_url'] . '/index.html'
		);

		$label = ! empty( $this->args['menu_label'] ) ? (string) $this->args['menu_label'] : __( 'Site Compare', 'binary-wp-admin-guide' );
		$saved = isset( $_GET['updated'] ) && '1' === (string) $_GET['updated'];
		?>
		<div class="wrap binary-wp-admin-guide-compare">
			<h1><?php echo esc_html( $label ); ?></h1>
			<p class="description" style="max-width:900px;">
				<?php esc_html_e( 'Full-height screenshots of every URL harvested from the source sitemap, captured on both origins and shown side by side. Refresh (per page, inside the gallery) re-captures both sides in place; Regenerate rebuilds the selected set.', 'binary-wp-admin-guide' ); ?>
			</p>

			<?php if ( $saved ) : ?>
				<div class="notice notice-success is-dismissible">
					<p><?php esc_html_e( 'Compare settings saved.', 'binary-wp-admin-guide' ); ?></p>
				</div>
			<?php endif; ?>

			<?php $this->render_settings_form( $settings ); ?>

			<?php $src_summary = $this->source_summary( $cfg ); ?>
			<div id="bwp-compare-source" style="display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin:0 0 1em;font-size:12px;color:#50575e;">
				<strong><?php esc_html_e( 'Source sitemap:', 'binary-wp-admin-guide' ); ?></strong>
				<span id="bwp-compare-source-summary"><?php echo esc_html( '' !== $src_summary ? $src_summary : __( 'not harvested yet', 'binary-wp-admin-guide' ) ); ?></span>
				<button type="button" class="button button-small" id="bwp-compare-refresh-sitemap" <?php disabled( ! $cfg['ready'] ); ?>>↻ <?php esc_html_e( 'Refresh sitemap data', 'binary-wp-admin-guide' ); ?></button>
			</div>

			<?php if ( ! $cfg['ready'] ) : ?>
				<div class="notice notice-warning inline" style="margin:1em 0;">
					<p>
						<?php esc_html_e( 'Capture toolbar disabled — the following are missing or unavailable:', 'binary-wp-admin-guide' ); ?>
						<code><?php echo esc_html( implode( ', ', $cfg['missing'] ) ); ?></code>.
						<?php esc_html_e( 'Settings and the read-only gallery still work. Run the capture tool from the terminal instead.', 'binary-wp-admin-guide' ); ?>
					</p>
				</div>
			<?php endif; ?>

			<div id="bwp-compare-toolbar" style="display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin:1em 0;">
				<label style="font-size:12px;color:#50575e;"><?php esc_html_e( 'Source', 'binary-wp-admin-guide' ); ?>
					<select id="bwp-compare-mode" <?php disabled( ! $cfg['ready'] ); ?>>
						<option value="full"><?php esc_html_e( 'Full sitemap (every page)', 'binary-wp-admin-guide' ); ?></option>
						<option value="demo"><?php esc_html_e( 'Demo (nav menu subset)', 'binary-wp-admin-guide' ); ?></option>
						<?php $types = $this->types( $cfg ); ?>
						<?php if ( $types ) : ?>
							<optgroup label="<?php esc_attr_e( 'Only one post type', 'binary-wp-admin-guide' ); ?>">
								<?php foreach ( $types as $slug => $count ) : ?>
									<option value="type:<?php echo esc_attr( $slug ); ?>"><?php echo esc_html( $slug . ' (' . $count . ')' ); ?></option>
								<?php endforeach; ?>
							</optgroup>
						<?php endif; ?>
					</select>
				</label>
				<label style="font-size:12px;color:#50575e;" title="<?php esc_attr_e( 'Capture only the first N pages of the selected source (empty = all).', 'binary-wp-admin-guide' ); ?>">
					<?php esc_html_e( 'first', 'binary-wp-admin-guide' ); ?>
					<input type="number" id="bwp-compare-limit" min="1" placeholder="<?php esc_attr_e( 'all', 'binary-wp-admin-guide' ); ?>" style="width:64px;" <?php disabled( ! $cfg['ready'] ); ?>>
				</label>
				<label style="font-size:12px;color:#50575e;" title="<?php esc_attr_e( 'Skip pages already captured OK; only shoot missing/failed ones (also resumes a crashed run).', 'binary-wp-admin-guide' ); ?>">
					<input type="checkbox" id="bwp-compare-incremental" checked <?php disabled( ! $cfg['ready'] ); ?>>
					<?php esc_html_e( 'incremental (missing only)', 'binary-wp-admin-guide' ); ?>
				</label>
				<label style="font-size:12px;color:#50575e;" title="<?php esc_attr_e( 'Capture every page, but only ONE representative (most recently modified) of each other post type — one shot per layout instead of every post/CPT item.', 'binary-wp-admin-guide' ); ?>">
					<input type="checkbox" id="bwp-compare-typical" <?php disabled( ! $cfg['ready'] ); ?>>
					<?php esc_html_e( 'typical layouts only (1 per CPT, all pages)', 'binary-wp-admin-guide' ); ?>
				</label>
				<button class="button button-primary" id="bwp-compare-run" <?php disabled( ! $cfg['ready'] ); ?>>↻ <?php esc_html_e( 'Regenerate', 'binary-wp-admin-guide' ); ?></button>
				<button class="button" id="bwp-compare-stop" style="display:none;">■ <?php esc_html_e( 'Stop', 'binary-wp-admin-guide' ); ?></button>
				<span id="bwp-compare-status" style="color:#50575e;font-size:12px;"><?php echo esc_html( $this->summary( $cfg ) ); ?></span>
				<?php if ( $has_gallery ) : ?>
					<a class="button button-link" href="<?php echo esc_url( $cfg['out_url'] . '/index.html' ); ?>" target="_blank" style="margin-left:auto;"><?php esc_html_e( 'Open gallery in new tab', 'binary-wp-admin-guide' ); ?> ↗</a>
				<?php endif; ?>
			</div>

			<?php if ( $has_gallery ) : ?>
				<iframe id="bwp-compare-frame" src="<?php echo esc_url( $iframe_src ); ?>"
					style="width:100%;height:80vh;border:1px solid #c3c4c7;border-radius:8px;background:#0f1115;"></iframe>
			<?php else : ?>
				<p><em><?php esc_html_e( 'No gallery generated yet.', 'binary-wp-admin-guide' ); ?></em>
				<?php esc_html_e( 'Save the URLs above, then click Regenerate to run the first capture.', 'binary-wp-admin-guide' ); ?></p>
			<?php endif; ?>

			<?php $this->render_inventory( $cfg ); ?>
		</div>
		<?php
		$this->render_toolbar_script( $ctl_nonce );
	}

	/** Settings form: the three URL fields, saved via admin-post. */
	private function render_settings_form( array $settings ) {
		?>
		<form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" style="background:#fff;border:1px solid #c3c4c7;padding:12px 16px;max-width:900px;margin:1em 0;">
			<?php wp_nonce_field( $this->context->nonce_action( 'compare_settings' ) ); ?>
			<input type="hidden" name="action" value="<?php echo esc_attr( $this->context->action_name( 'compare_save_settings' ) ); ?>">
			<table class="form-table" role="presentation" style="margin-top:0;">
				<tr>
					<th scope="row"><label for="bwp-compare-source-base"><?php esc_html_e( 'Source base URL', 'binary-wp-admin-guide' ); ?></label></th>
					<td>
						<input type="url" class="regular-text code" id="bwp-compare-source-base" name="source_base" value="<?php echo esc_attr( $settings['source_base'] ); ?>" placeholder="https://www.example.com">
						<p class="description"><?php esc_html_e( 'Origin of the reference (production) site.', 'binary-wp-admin-guide' ); ?></p>
					</td>
				</tr>
				<tr>
					<th scope="row"><label for="bwp-compare-source-sitemap"><?php esc_html_e( 'Source sitemap URL', 'binary-wp-admin-guide' ); ?></label></th>
					<td>
						<input type="url" class="regular-text code" id="bwp-compare-source-sitemap" name="source_sitemap" value="<?php echo esc_attr( $settings['source_sitemap'] ); ?>" placeholder="https://www.example.com/sitemap_index.xml">
						<p class="description"><?php esc_html_e( 'Sitemap (index) the URL list is scraped from.', 'binary-wp-admin-guide' ); ?></p>
					</td>
				</tr>
				<tr>
					<th scope="row"><label for="bwp-compare-target-base"><?php esc_html_e( 'Target base URL', 'binary-wp-admin-guide' ); ?></label></th>
					<td>
						<input type="url" class="regular-text code" id="bwp-compare-target-base" name="target_base" value="<?php echo esc_attr( $settings['target_base'] ); ?>" placeholder="<?php echo esc_attr( home_url() ); ?>">
						<p class="description"><?php esc_html_e( 'Origin the same paths are captured on for comparison (usually this site).', 'binary-wp-admin-guide' ); ?></p>
					</td>
				</tr>
			</table>
			<?php submit_button( __( 'Save Compare Settings', 'binary-wp-admin-guide' ), 'secondary', 'submit', false ); ?>
		</form>
		<?php
	}

	/** Collapsible URL inventory read from manifest.json (the scraped URL list). */
	private function render_inventory( array $cfg ) {
		$m = $this->manifest( $cfg );
		if ( ! $m ) {
			return;
		}
		$pages = isset( $m['pages'] ) ? (array) $m['pages'] : array();
		if ( ! $pages ) {
			return;
		}
		?>
		<details style="margin:1.5em 0;">
			<summary style="cursor:pointer;font-weight:600;">
				<?php
				printf(
					/* translators: %d: number of URLs in the captured inventory */
					esc_html__( 'URL inventory (%d paths)', 'binary-wp-admin-guide' ),
					(int) count( $pages )
				);
				?>
			</summary>
			<table class="widefat striped" style="margin-top:8px;max-width:1100px;">
				<thead>
					<tr>
						<th><?php esc_html_e( 'Path', 'binary-wp-admin-guide' ); ?></th>
						<th><?php esc_html_e( 'Type', 'binary-wp-admin-guide' ); ?></th>
						<th><?php esc_html_e( 'Section', 'binary-wp-admin-guide' ); ?></th>
						<th><?php esc_html_e( 'Source HTTP', 'binary-wp-admin-guide' ); ?></th>
						<th><?php esc_html_e( 'Target HTTP', 'binary-wp-admin-guide' ); ?></th>
						<th title="<?php esc_attr_e( 'Target page height minus source page height (px)', 'binary-wp-admin-guide' ); ?>">Δ <?php esc_html_e( 'height', 'binary-wp-admin-guide' ); ?></th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ( $pages as $p ) :
						$prod  = isset( $p['prod'] ) && is_array( $p['prod'] ) ? $p['prod'] : array();
						$local = isset( $p['local'] ) && is_array( $p['local'] ) ? $p['local'] : array();
						$ph    = isset( $prod['height'] ) ? (int) $prod['height'] : 0;
						$lh    = isset( $local['height'] ) ? (int) $local['height'] : 0;
						$delta = ( $ph && $lh ) ? ( $lh - $ph ) : null;
					?>
						<tr>
							<td><code><?php echo esc_html( isset( $p['path'] ) ? (string) $p['path'] : '' ); ?></code></td>
							<td><?php echo esc_html( isset( $p['type'] ) ? (string) $p['type'] : '—' ); ?></td>
							<td><?php echo esc_html( isset( $p['section'] ) ? (string) $p['section'] : '—' ); ?></td>
							<td><?php echo esc_html( isset( $prod['status'] ) ? (string) $prod['status'] : '—' ); ?></td>
							<td><?php echo esc_html( isset( $local['status'] ) ? (string) $local['status'] : '—' ); ?></td>
							<td><?php echo esc_html( null === $delta ? '—' : sprintf( '%+d px', $delta ) ); ?></td>
						</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
		</details>
		<?php
	}

	/** Toolbar behavior: regenerate / stop / status poll, gallery reload. */
	private function render_toolbar_script( $ctl_nonce ) {
		$actions = array(
			'regenerate'      => $this->context->action_name( 'compare_regenerate' ),
			'stop'            => $this->context->action_name( 'compare_stop' ),
			'status'          => $this->context->action_name( 'compare_status' ),
			'refresh_sitemap' => $this->context->action_name( 'compare_refresh_sitemap' ),
		);
		?>
		<script>
		(function () {
			const ajaxurl  = <?php echo wp_json_encode( admin_url( 'admin-ajax.php' ) ); ?>;
			const nonce    = <?php echo wp_json_encode( $ctl_nonce ); ?>;
			const actions  = <?php echo wp_json_encode( $actions ); ?>;
			const statusEl = document.getElementById('bwp-compare-status');
			const runBtn   = document.getElementById('bwp-compare-run');
			const stopBtn  = document.getElementById('bwp-compare-stop');
			const modeSel  = document.getElementById('bwp-compare-mode');
			const incChk   = document.getElementById('bwp-compare-incremental');
			const typChk   = document.getElementById('bwp-compare-typical');
			const limitInp = document.getElementById('bwp-compare-limit');
			const smBtn    = document.getElementById('bwp-compare-refresh-sitemap');
			const smEl     = document.getElementById('bwp-compare-source-summary');
			let polling = null;

			function post(action, extra) {
				const body = new URLSearchParams(Object.assign({ action, _ajax_nonce: nonce }, extra || {}));
				return fetch(ajaxurl, { method: 'POST', body }).then(r => r.json());
			}
			function reloadFrame() {
				const f = document.getElementById('bwp-compare-frame');
				if (f) { const u = new URL(f.src); u.searchParams.set('cb', Date.now()); f.src = u.toString(); }
				else { location.reload(); }
			}
			function running(on) {
				if (runBtn) runBtn.disabled = on;
				if (modeSel) modeSel.disabled = on;
				if (incChk) incChk.disabled = on;
				if (typChk) typChk.disabled = on;
				if (smBtn) smBtn.disabled = on;
				if (stopBtn) stopBtn.style.display = on ? '' : 'none';
			}

			// Refresh sitemap data: re-harvest the source sitemap (no capture) so the
			// source count + per-type options reflect the current sitemap. Reloads
			// the page on success so the Source dropdown regenerates server-side.
			if (smBtn) smBtn.addEventListener('click', () => {
				smBtn.disabled = true;
				if (smEl) smEl.textContent = 'refreshing…';
				post(actions.refresh_sitemap).then(res => {
					if (res && res.success) {
						if (smEl) smEl.textContent = res.data.summary || '';
						location.reload();
					} else {
						smBtn.disabled = false;
						if (smEl) smEl.textContent = 'refresh failed: ' + ((res && res.data && res.data.message) || 'error');
					}
				});
			});

			let lastProgress = '';
			function poll() {
				post(actions.status).then(res => {
					if (!res || !res.success) return;
					const d = res.data;
					if (d.running) {
						running(true);
						statusEl.textContent = 'capturing… ' + (d.progress || '');
						// Live progress: refresh the gallery as new shots land, but
						// only when the progress line actually advanced (avoid jank).
						if (d.progress && d.progress !== lastProgress) { lastProgress = d.progress; reloadFrame(); }
					} else {
						statusEl.textContent = d.summary || '';
						clearInterval(polling); polling = null; running(false);
						reloadFrame();
					}
				});
			}
			function startPolling() { if (!polling) polling = setInterval(poll, 3000); }

			if (runBtn) runBtn.addEventListener('click', () => {
				const mode = modeSel ? modeSel.value : 'demo';
				const incremental = incChk ? incChk.checked : true;
				const typical = typChk ? typChk.checked : false;
				const limit = limitInp && limitInp.value ? parseInt(limitInp.value, 10) : 0;
				if (mode === 'full' && !incremental && !typical && !limit && !confirm('Full re-capture of the WHOLE sitemap (not incremental) can take many minutes. Continue?')) return;
				running(true); statusEl.textContent = 'starting ' + mode + (typical ? ' · typical' : '') + (limit ? ' · first ' + limit : '') + (incremental ? ' · incremental' : '') + '…';
				post(actions.regenerate, { mode, incremental: incremental ? '1' : '0', typical: typical ? '1' : '0', limit: String(limit || 0) }).then(res => {
					if (!res || !res.success) { running(false); statusEl.textContent = 'failed: ' + ((res && res.data && res.data.message) || 'error'); return; }
					startPolling();
				});
			});

			if (stopBtn) stopBtn.addEventListener('click', () => {
				stopBtn.disabled = true;
				post(actions.stop).then(() => { stopBtn.disabled = false; poll(); });
			});

			// Button label always reflects the selected source (+ limit) so it's
			// unmistakable what a click will capture.
			function syncBtn() {
				if (!runBtn || !modeSel) return;
				const typ = typChk && typChk.checked ? ' · typical' : '';
				const lim = limitInp && limitInp.value ? ' · first ' + limitInp.value : '';
				runBtn.textContent = '↻ Regenerate — ' + modeSel.options[modeSel.selectedIndex].text + typ + lim;
			}
			if (modeSel) modeSel.addEventListener('change', syncBtn);
			if (limitInp) limitInp.addEventListener('input', syncBtn);
			if (typChk) typChk.addEventListener('change', syncBtn);
			if (modeSel) syncBtn();

			// If a run is already going (started elsewhere / CLI), pick it up on load.
			post(actions.status).then(res => { if (res && res.success && res.data.running) startPolling(); });
		})();
		</script>
		<?php
	}

	// ── Settings save (admin-post) ──────────────────────────────────────

	public function handle_save_settings() {
		if ( ! current_user_can( $this->capability() ) ) {
			wp_die( esc_html__( 'Forbidden', 'binary-wp-admin-guide' ), 403 );
		}
		check_admin_referer( $this->context->nonce_action( 'compare_settings' ) );

		$settings = array();
		foreach ( array( 'source_base', 'source_sitemap', 'target_base' ) as $key ) {
			$raw = isset( $_POST[ $key ] ) ? trim( (string) wp_unslash( $_POST[ $key ] ) ) : '';
			$settings[ $key ] = '' === $raw ? '' : esc_url_raw( $raw );
		}
		// Origins shouldn't carry a trailing slash (paths are absolute, start with /).
		$settings['source_base'] = untrailingslashit( $settings['source_base'] );
		$settings['target_base'] = untrailingslashit( $settings['target_base'] );

		update_option( $this->context->option_key( 'compare' ), $settings, false );

		// Refresh the source inventory (sitemap.json) so the page/type counts
		// reflect the sitemap URL just saved — this is what keeps the "source"
		// info valid over time instead of stranding a stale count from the last
		// capture. Best-effort + synchronous (harvest is a quick XML fetch).
		$cfg     = $this->config();
		$harvest = $this->harvest_command( $cfg );
		if ( $harvest && $this->shell_available() ) {
			@shell_exec( $harvest );
		}

		wp_safe_redirect( add_query_arg(
			array( 'page' => $this->page_slug, 'updated' => '1' ),
			admin_url( 'admin.php' )
		) );
		exit;
	}

	// ── AJAX: refresh the source sitemap inventory (harvest-only) ───────

	/**
	 * Re-harvest the source sitemap and rewrite sitemap.json — no capture, no
	 * browser. Backs the "Refresh sitemap data" button so the source page/type
	 * counts can be brought current on demand.
	 */
	public function ajax_refresh_sitemap() {
		if ( ! current_user_can( $this->capability() ) ) {
			wp_send_json_error( array( 'message' => 'forbidden' ), 403 );
		}
		check_ajax_referer( $this->context->nonce_action( 'compare_ctl' ) );
		@set_time_limit( 120 );

		$cfg = $this->config();
		if ( ! $cfg['ready'] ) {
			wp_send_json_error( array( 'message' => 'capture tool unavailable (' . implode( ', ', $cfg['missing'] ) . ')' ) );
		}
		$harvest = $this->harvest_command( $cfg );
		if ( ! $harvest ) {
			wp_send_json_error( array( 'message' => 'no source sitemap configured' ) );
		}
		if ( ! is_dir( $cfg['out_dir'] ) ) {
			wp_mkdir_p( $cfg['out_dir'] );
		}
		$out  = (string) shell_exec( $harvest );
		$data = $this->sitemap_data( $cfg );
		if ( ! $data ) {
			wp_send_json_error( array( 'message' => 'harvest produced no data', 'raw' => mb_substr( $out, 0, 500 ) ) );
		}
		wp_send_json_success( array(
			'summary' => $this->source_summary( $cfg ),
			'total'   => isset( $data['total'] ) ? (int) $data['total'] : 0,
			'types'   => isset( $data['types'] ) ? (array) $data['types'] : array(),
		) );
	}

	// ── AJAX: refresh a set of paths (both sides) in place ──────────────

	public function ajax_refresh() {
		if ( ! current_user_can( $this->capability() ) ) {
			wp_send_json_error( array( 'message' => 'forbidden' ), 403 );
		}
		check_ajax_referer( $this->context->nonce_action( 'compare_refresh' ) );
		@set_time_limit( 300 );

		$cfg = $this->config();
		if ( ! $cfg['ready'] ) {
			wp_send_json_error( array( 'message' => 'capture tool unavailable (' . implode( ', ', $cfg['missing'] ) . ')' ) );
		}
		$paths = json_decode( isset( $_POST['paths'] ) ? wp_unslash( (string) $_POST['paths'] ) : '[]', true );
		$paths = is_array( $paths ) ? $this->sanitize_paths( $paths ) : array();
		if ( ! $paths ) {
			wp_send_json_error( array( 'message' => 'no valid paths' ) );
		}

		$cmd = sprintf(
			'%s %s --out %s --paths %s 2>/dev/null',
			escapeshellarg( $cfg['node'] ),
			escapeshellarg( $cfg['tool_dir'] . '/refresh-cli.mjs' ),
			escapeshellarg( $cfg['out_dir'] ),
			escapeshellarg( (string) wp_json_encode( $paths ) )
		);
		$out = (string) shell_exec( $cmd );
		$res = json_decode( $out, true );
		if ( ! is_array( $res ) || isset( $res['error'] ) ) {
			wp_send_json_error( array(
				'message' => isset( $res['error'] ) ? $res['error'] : 'refresh failed',
				'raw'     => mb_substr( $out, 0, 500 ),
			) );
		}
		wp_send_json_success( array( 'pages' => isset( $res['pages'] ) ? $res['pages'] : array() ) );
	}

	// ── AJAX: kick off a detached regenerate run ────────────────────────

	public function ajax_regenerate() {
		if ( ! current_user_can( $this->capability() ) ) {
			wp_send_json_error( array( 'message' => 'forbidden' ), 403 );
		}
		check_ajax_referer( $this->context->nonce_action( 'compare_ctl' ) );

		$cfg = $this->config();
		if ( ! $cfg['ready'] ) {
			wp_send_json_error( array( 'message' => 'capture tool unavailable (' . implode( ', ', $cfg['missing'] ) . ')' ) );
		}
		if ( $this->is_running( $cfg ) ) {
			wp_send_json_error( array( 'message' => 'a run is already in progress' ) );
		}

		// `mode` = source set: full | demo | smoke | type:<sitemap-type>.
		// NOTE: validated via regex on the RAW value — sanitize_key() would
		// strip the colon out of `type:x`.
		$mode_raw = isset( $_POST['mode'] ) ? (string) wp_unslash( $_POST['mode'] ) : 'full';
		if ( ! preg_match( '/^(full|demo|smoke|type:[a-z0-9_\-]+)$/', $mode_raw ) ) {
			$mode_raw = 'full';
		}
		$mode = $mode_raw;
		if ( 'demo' === $mode ) {
			$args = '--demo';
		} elseif ( 0 === strpos( $mode, 'type:' ) ) {
			$args = '--types ' . substr( $mode, 5 ); // regex-validated slug, shell-safe
		} elseif ( 'smoke' === $mode ) {
			$args = '--limit 10';
		} else {
			$args = ''; // wrapper default = full sitemap
		}
		$limit = isset( $_POST['limit'] ) ? absint( $_POST['limit'] ) : 0;
		if ( $limit > 0 && 'smoke' !== $mode ) {
			$args = trim( $args . ' --limit ' . $limit );
		}
		$incremental = ! empty( $_POST['incremental'] ) && 'false' !== $_POST['incremental'];
		if ( $incremental ) {
			$args = trim( $args . ' --incremental' );
		}
		// "typical layouts only": one representative per non-page type, all pages.
		$typical = ! empty( $_POST['typical'] ) && 'false' !== $_POST['typical'] && '0' !== (string) $_POST['typical'];
		if ( $typical ) {
			$args = trim( $args . ' --typical' );
		}

		// Saved settings drive the capture: source sitemap (the URL scraper),
		// source origin, target origin, plus the configured output dir.
		$settings = $this->settings();
		if ( '' !== $settings['source_sitemap'] ) {
			$args = trim( $args . ' --sitemap ' . escapeshellarg( $settings['source_sitemap'] ) );
		}
		if ( '' !== $settings['source_base'] ) {
			$args = trim( $args . ' --prod-base ' . escapeshellarg( untrailingslashit( $settings['source_base'] ) ) );
		}
		if ( '' !== $settings['target_base'] ) {
			$args = trim( $args . ' --local-base ' . escapeshellarg( untrailingslashit( $settings['target_base'] ) ) );
		}
		$args = trim( $args . ' --out ' . escapeshellarg( $cfg['out_dir'] ) );

		if ( ! is_dir( $cfg['out_dir'] ) ) {
			wp_mkdir_p( $cfg['out_dir'] );
		}
		$lock = $this->lock_file( $cfg );
		$log  = $this->log_file( $cfg );
		@file_put_contents( $lock, 'starting' ); // claim; the run overwrites with its PID

		// Detached: the inner shell writes its own PID into the lock first (so
		// the status poller can check the process is actually alive — a died
		// run's lock then reads as stale instantly), runs the wrapper, and
		// drops the lock on exit. PATH is set explicitly (node dir + standard
		// bins) and bash is called by absolute path — a detached session can
		// inherit a stripped PATH where even `bash` isn't found.
		$inner = sprintf(
			'echo $$ > %s; export PATH=%s:/usr/local/bin:/usr/bin:/bin:"$PATH"; /bin/bash %s %s > %s 2>&1; rm -f %s',
			escapeshellarg( $lock ),
			escapeshellarg( dirname( $cfg['node'] ) ),
			escapeshellarg( $cfg['wrapper'] ),
			$args,
			escapeshellarg( $log ),
			escapeshellarg( $lock )
		);
		$this->spawn_detached( $inner );

		wp_send_json_success( array( 'started' => true, 'mode' => $mode, 'incremental' => $incremental ) );
	}

	// ── AJAX: stop a running regenerate ─────────────────────────────────

	public function ajax_stop() {
		if ( ! current_user_can( $this->capability() ) ) {
			wp_send_json_error( array( 'message' => 'forbidden' ), 403 );
		}
		check_ajax_referer( $this->context->nonce_action( 'compare_ctl' ) );

		$cfg  = $this->config();
		$lock = $this->lock_file( $cfg );
		$pid  = file_exists( $lock ) ? (int) trim( (string) @file_get_contents( $lock ) ) : 0;
		if ( $this->shell_available() ) {
			// Kill the detached wrapper shell, then sweep the actual capture
			// process (macOS has no setsid, so no process-group kill).
			if ( $pid > 0 ) {
				shell_exec( 'kill -TERM ' . (int) $pid . ' 2>/dev/null' );
			}
			if ( '' !== $cfg['tool_dir'] ) {
				shell_exec( 'pkill -f ' . escapeshellarg( $cfg['tool_dir'] . '/capture.mjs' ) . ' 2>/dev/null' );
			}
		}
		@unlink( $lock );
		wp_send_json_success( array( 'stopped' => true ) );
	}

	// ── AJAX: poll regenerate status + manifest summary ─────────────────

	public function ajax_status() {
		if ( ! current_user_can( $this->capability() ) ) {
			wp_send_json_error( array( 'message' => 'forbidden' ), 403 );
		}
		check_ajax_referer( $this->context->nonce_action( 'compare_ctl' ) );

		$cfg     = $this->config();
		$running = $this->is_running( $cfg );

		// Last capture line from the log as a coarse progress indicator.
		$progress = '';
		$log      = $this->log_file( $cfg );
		if ( $running && file_exists( $log ) ) {
			$lines = array_values( array_filter( array_map( 'trim', (array) @file( $log ) ) ) );
			for ( $i = count( $lines ) - 1; $i >= 0; $i-- ) {
				if ( 0 === strpos( $lines[ $i ], '[' ) || 0 === strpos( $lines[ $i ], 'Reading' ) || 0 === strpos( $lines[ $i ], 'Harvesting' ) ) {
					$progress = $lines[ $i ];
					break;
				}
			}
		}

		wp_send_json_success( array(
			'running'  => $running,
			'progress' => $progress,
			'summary'  => $this->summary( $cfg ),
		) );
	}
}
